create database if not exists `gcstest`;
use gcstest;
drop table if exists `Clients`;
create table Clients (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	city VARCHAR(50),
	state VARCHAR(50),
	postal_code VARCHAR(50),
	email VARCHAR(50),
	phone VARCHAR(50)
);
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (1, 'Janet', 'Schmidt', 'Columbia', 'South Carolina', '29240', 'jschmidt0@zimbio.com', '1-(803)629-5899');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (2, 'Martha', 'Greene', 'Denver', 'Colorado', '80204', 'mgreene1@google.com.hk', '1-(303)590-3691');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (3, 'Laura', 'Kennedy', 'Brooklyn', 'New York', '11210', 'lkennedy2@scribd.com', '1-(718)735-8708');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (4, 'Stephen', 'Cooper', 'Salem', 'Oregon', '97306', 'scooper3@ft.com', '1-(503)602-9884');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (5, 'Betty', 'Hicks', 'Saint Cloud', 'Minnesota', '56398', 'bhicks4@mapy.cz', '1-(320)567-0426');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (6, 'Earl', 'Little', 'Detroit', 'Michigan', '48295', 'elittle5@ovh.net', '1-(313)692-3661');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (7, 'Lois', 'Porter', 'Las Vegas', 'Nevada', '89135', 'lporter6@nbcnews.com', '1-(702)937-2259');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (8, 'Chris', 'Andrews', 'Irvine', 'California', '92619', 'candrews7@psu.edu', '1-(949)749-4532');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (9, 'James', 'Austin', 'Tulsa', 'Oklahoma', '74108', 'jaustin8@nyu.edu', '1-(918)951-4915');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (10, 'Walter', 'Fisher', 'Daytona Beach', 'Florida', '32118', 'wfisher9@cnet.com', '1-(386)990-8087');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (11, 'Emily', 'Fernandez', 'Young America', 'Minnesota', '55573', 'efernandeza@hhs.gov', '1-(952)843-6014');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (12, 'Gary', 'Davis', 'Las Vegas', 'Nevada', '89166', 'gdavisb@go.com', '1-(702)339-5823');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (13, 'Jennifer', 'Howard', 'Garden Grove', 'California', '92645', 'jhowardc@sina.com.cn', '1-(714)729-2404');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (14, 'Jimmy', 'Greene', 'Boise', 'Idaho', '83711', 'jgreened@indiegogo.com', '1-(208)449-2803');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (15, 'Christopher', 'Nelson', 'San Diego', 'California', '92127', 'cnelsone@a8.net', '1-(858)703-5569');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (16, 'Janet', 'James', 'Arlington', 'Texas', '76011', 'jjamesf@cisco.com', '1-(214)507-1469');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (17, 'Rachel', 'Harvey', 'Danbury', 'Connecticut', '06816', 'rharveyg@xrea.com', '1-(203)568-0354');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (18, 'Philip', 'Griffin', 'El Paso', 'Texas', '79950', 'pgriffinh@ehow.com', '1-(915)808-2691');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (19, 'Bonnie', 'Rose', 'Austin', 'Texas', '78737', 'brosei@aol.com', '1-(512)252-1102');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (20, 'Heather', 'Chapman', 'Charleston', 'West Virginia', '25326', 'hchapmanj@mapquest.com', '1-(304)271-1743');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (21, 'Tammy', 'Price', 'Anderson', 'South Carolina', '29625', 'tpricek@rakuten.co.jp', '1-(864)510-8055');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (22, 'Billy', 'Alvarez', 'Columbus', 'Ohio', '43240', 'balvarezl@csmonitor.com', '1-(740)633-4958');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (23, 'Douglas', 'Smith', 'Rochester', 'New York', '14652', 'dsmithm@dot.gov', '1-(585)444-4575');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (24, 'Andrea', 'Arnold', 'Indianapolis', 'Indiana', '46295', 'aarnoldn@imgur.com', '1-(317)353-6271');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (25, 'Earl', 'Johnson', 'Littleton', 'Colorado', '80161', 'ejohnsono@hatena.ne.jp', '1-(303)489-2825');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (26, 'Kelly', 'Porter', 'White Plains', 'New York', '10606', 'kporterp@cnbc.com', '1-(914)105-9253');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (27, 'John', 'Rogers', 'Boise', 'Idaho', '83711', 'jrogersq@freewebs.com', '1-(208)600-3819');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (28, 'Mary', 'Rivera', 'Nashville', 'Tennessee', '37250', 'mriverar@chron.com', '1-(615)122-8419');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (29, 'Emily', 'Hunt', 'Richmond', 'Virginia', '23242', 'ehunts@npr.org', '1-(804)711-2112');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (30, 'Scott', 'Moreno', 'Lexington', 'Kentucky', '40515', 'smorenot@simplemachines.org', '1-(859)171-5149');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (31, 'Gerald', 'Fox', 'Duluth', 'Georgia', '30096', 'gfoxu@forbes.com', '1-(678)997-7001');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (32, 'Jesse', 'Elliott', 'Johnstown', 'Pennsylvania', '15906', 'jelliottv@symantec.com', '1-(814)356-3582');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (33, 'Margaret', 'Roberts', 'Kingsport', 'Tennessee', '37665', 'mrobertsw@ihg.com', '1-(423)754-2556');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (34, 'Tammy', 'Moore', 'Norfolk', 'Virginia', '23520', 'tmoorex@abc.net.au', '1-(757)310-0298');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (35, 'Christina', 'Taylor', 'Oakland', 'California', '94622', 'ctaylory@trellian.com', '1-(510)911-4389');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (36, 'Diana', 'Little', 'Dallas', 'Texas', '75387', 'dlittlez@cmu.edu', '1-(214)877-2266');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (37, 'Diana', 'Lynch', 'Roanoke', 'Virginia', '24020', 'dlynch10@behance.net', '1-(540)655-9687');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (38, 'Ronald', 'Owens', 'Houston', 'Texas', '77234', 'rowens11@prnewswire.com', '1-(713)399-6856');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (39, 'Bobby', 'Watson', 'Louisville', 'Kentucky', '40220', 'bwatson12@barnesandnoble.com', '1-(502)161-1271');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (40, 'Timothy', 'Hamilton', 'Fairbanks', 'Alaska', '99790', 'thamilton13@comcast.net', '1-(907)441-2995');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (41, 'Louis', 'Dunn', 'Atlanta', 'Georgia', '30328', 'ldunn14@webs.com', '1-(770)858-7416');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (42, 'Ashley', 'Davis', 'Phoenix', 'Arizona', '85099', 'adavis15@rambler.ru', '1-(602)262-9358');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (43, 'Michael', 'Perry', 'Boise', 'Idaho', '83716', 'mperry16@nps.gov', '1-(208)357-8608');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (44, 'Donald', 'Hart', 'Los Angeles', 'California', '90189', 'dhart17@unesco.org', '1-(213)425-4830');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (45, 'Wayne', 'Edwards', 'Naperville', 'Illinois', '60567', 'wedwards18@redcross.org', '1-(630)570-0684');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (46, 'Steven', 'Spencer', 'Mesquite', 'Texas', '75185', 'sspencer19@weather.com', '1-(214)357-8256');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (47, 'Ryan', 'Larson', 'Vancouver', 'Washington', '98687', 'rlarson1a@marketwatch.com', '1-(360)483-9610');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (48, 'Daniel', 'Mendoza', 'Corpus Christi', 'Texas', '78470', 'dmendoza1b@xing.com', '1-(361)660-5018');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (49, 'Willie', 'James', 'Chicago', 'Illinois', '60669', 'wjames1c@ucoz.com', '1-(312)159-2015');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (50, 'Jane', 'West', 'Oklahoma City', 'Oklahoma', '73109', 'jwest1d@usatoday.com', '1-(405)635-6705');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (51, 'Teresa', 'West', 'Annapolis', 'Maryland', '21405', 'twest1e@netlog.com', '1-(301)130-0313');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (52, 'Ryan', 'Sanchez', 'Jacksonville', 'Florida', '32204', 'rsanchez1f@parallels.com', '1-(904)344-5879');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (53, 'Paul', 'Torres', 'Columbia', 'South Carolina', '29240', 'ptorres1g@wsj.com', '1-(803)829-9676');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (54, 'Richard', 'Mcdonald', 'Arvada', 'Colorado', '80005', 'rmcdonald1h@msn.com', '1-(720)859-5101');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (55, 'Russell', 'Ramos', 'Bakersfield', 'California', '93399', 'rramos1i@arizona.edu', '1-(661)798-5398');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (56, 'Amanda', 'Arnold', 'Savannah', 'Georgia', '31410', 'aarnold1j@answers.com', '1-(912)193-2950');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (57, 'Lawrence', 'Campbell', 'Portsmouth', 'New Hampshire', '03804', 'lcampbell1k@mozilla.org', '1-(603)636-3668');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (58, 'Gerald', 'Baker', 'Charleston', 'West Virginia', '25389', 'gbaker1l@nifty.com', '1-(304)146-8901');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (59, 'Scott', 'Kennedy', 'New Castle', 'Pennsylvania', '16107', 'skennedy1m@free.fr', '1-(724)527-2662');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (60, 'Donald', 'Chapman', 'Santa Ana', 'California', '92705', 'dchapman1n@economist.com', '1-(213)711-8636');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (61, 'Julie', 'Day', 'Birmingham', 'Alabama', '35231', 'jday1o@tinypic.com', '1-(205)796-1602');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (62, 'Robert', 'Mcdonald', 'Oxnard', 'California', '93034', 'rmcdonald1p@t.co', '1-(805)591-4469');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (63, 'Mark', 'Reyes', 'Nashville', 'Tennessee', '37205', 'mreyes1q@twitter.com', '1-(615)421-9720');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (64, 'Gary', 'Thompson', 'Tacoma', 'Washington', '98464', 'gthompson1r@hhs.gov', '1-(253)438-4969');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (65, 'Donna', 'Harvey', 'Tuscaloosa', 'Alabama', '35405', 'dharvey1s@vk.com', '1-(205)901-0643');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (66, 'Diane', 'Ross', 'Chattanooga', 'Tennessee', '37416', 'dross1t@latimes.com', '1-(423)225-2773');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (67, 'Elizabeth', 'Pierce', 'Provo', 'Utah', '84605', 'epierce1u@list-manage.com', '1-(801)402-0265');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (68, 'Judith', 'Reid', 'Clearwater', 'Florida', '33763', 'jreid1v@cnet.com', '1-(727)174-2225');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (69, 'Adam', 'Webb', 'Saint Louis', 'Missouri', '63143', 'awebb1w@yolasite.com', '1-(314)346-9561');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (70, 'Ronald', 'Anderson', 'Hagerstown', 'Maryland', '21747', 'randerson1x@acquirethisname.com', '1-(240)443-5577');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (71, 'Howard', 'Young', 'Philadelphia', 'Pennsylvania', '19120', 'hyoung1y@hubpages.com', '1-(215)693-5388');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (72, 'Steve', 'Fernandez', 'Cincinnati', 'Ohio', '45208', 'sfernandez1z@technorati.com', '1-(513)684-0958');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (73, 'Carl', 'Little', 'Miami', 'Florida', '33129', 'clittle20@icq.com', '1-(786)272-1104');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (74, 'Deborah', 'Cox', 'Madison', 'Wisconsin', '53726', 'dcox21@umich.edu', '1-(608)340-3146');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (75, 'Donald', 'Ruiz', 'Charlotte', 'North Carolina', '28235', 'druiz22@sitemeter.com', '1-(704)220-4757');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (76, 'Albert', 'Wagner', 'Salt Lake City', 'Utah', '84130', 'awagner23@who.int', '1-(801)572-3667');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (77, 'Clarence', 'Kim', 'Houston', 'Texas', '77080', 'ckim24@paypal.com', '1-(832)133-1652');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (78, 'Steve', 'Oliver', 'Washington', 'District of Columbia', '20238', 'soliver25@latimes.com', '1-(202)119-8685');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (79, 'Wanda', 'Cole', 'Lehigh Acres', 'Florida', '33972', 'wcole26@jimdo.com', '1-(239)317-5249');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (80, 'Clarence', 'Little', 'Shreveport', 'Louisiana', '71161', 'clittle27@rambler.ru', '1-(318)485-7861');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (81, 'Ryan', 'Fields', 'Roanoke', 'Virginia', '24009', 'rfields28@dion.ne.jp', '1-(540)767-4721');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (82, 'Brenda', 'Scott', 'Schaumburg', 'Illinois', '60193', 'bscott29@pagesperso-orange.fr', '1-(224)938-7004');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (83, 'Jacqueline', 'Warren', 'Phoenix', 'Arizona', '85005', 'jwarren2a@census.gov', '1-(480)208-4199');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (84, 'Timothy', 'Crawford', 'Baton Rouge', 'Louisiana', '70894', 'tcrawford2b@pcworld.com', '1-(225)695-0312');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (85, 'Julie', 'Fox', 'Cincinnati', 'Ohio', '45213', 'jfox2c@ucsd.edu', '1-(513)461-2452');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (86, 'Johnny', 'Stewart', 'Houston', 'Texas', '77095', 'jstewart2d@youtube.com', '1-(832)417-4119');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (87, 'Andrea', 'Daniels', 'Orlando', 'Florida', '32813', 'adaniels2e@vk.com', '1-(407)599-0039');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (88, 'Patricia', 'Hughes', 'New York City', 'New York', '10131', 'phughes2f@meetup.com', '1-(212)696-5732');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (89, 'Andrea', 'Long', 'Corpus Christi', 'Texas', '78470', 'along2g@tinypic.com', '1-(361)497-4774');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (90, 'Jose', 'Ramirez', 'El Paso', 'Texas', '79945', 'jramirez2h@over-blog.com', '1-(915)424-0653');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (91, 'Paula', 'Bowman', 'Baltimore', 'Maryland', '21275', 'pbowman2i@bbc.co.uk', '1-(410)621-7614');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (92, 'Jane', 'Warren', 'Pensacola', 'Florida', '32575', 'jwarren2j@mlb.com', '1-(850)291-1939');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (93, 'Stephen', 'Davis', 'San Antonio', 'Texas', '78225', 'sdavis2k@dailymotion.com', '1-(210)269-7904');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (94, 'Linda', 'Matthews', 'Omaha', 'Nebraska', '68117', 'lmatthews2l@wsj.com', '1-(402)593-7719');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (95, 'Judy', 'Ward', 'Seattle', 'Washington', '98115', 'jward2m@discovery.com', '1-(425)386-4186');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (96, 'Paul', 'Hudson', 'Saint Louis', 'Missouri', '63196', 'phudson2n@google.de', '1-(314)869-6942');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (97, 'Jane', 'Gonzalez', 'Grand Junction', 'Colorado', '81505', 'jgonzalez2o@spiegel.de', '1-(970)987-8133');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (98, 'Elizabeth', 'Fowler', 'Knoxville', 'Tennessee', '37931', 'efowler2p@amazonaws.com', '1-(865)327-5713');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (99, 'Melissa', 'Watson', 'Torrance', 'California', '90505', 'mwatson2q@un.org', '1-(310)561-4065');
insert into Clients (id, first_name, last_name, city, state, postal_code, email, phone) values (100, 'Billy', 'Howell', 'San Francisco', 'California', '94105', 'bhowell2r@bloglines.com', '1-(310)460-6666');
